-- Ambia Database Schema (MySQL)
-- Migration 002: Ambient Events for iOS system integration
-- Adds support for Dynamic Island, Notifications, and Live Activities

USE ambia;

-- Ambient Events table (AI-generated live activities, notifications, and dynamic island updates)
CREATE TABLE IF NOT EXISTS ambient_events (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,

    -- Event classification
    event_type VARCHAR(50) NOT NULL CHECK (event_type IN (
        'live_activity',      -- Ongoing events (travel, deliveries, timers)
        'dynamic_island',     -- Brief glanceable updates
        'notification',       -- Important time-sensitive moments
        'background_update'   -- Silent updates to existing activities
    )),
    priority VARCHAR(20) NOT NULL CHECK (priority IN ('critical', 'high', 'medium', 'low')) DEFAULT 'medium',

    -- Event content (AI-generated by Claude)
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    body TEXT,

    -- Dynamic data structure (NO HARDCODING - Claude generates ANY structure)
    data JSON NOT NULL DEFAULT ('{}'), -- e.g. {"departure_time": "3:45 PM", "platform": "Track 7", "travel_time_mins": 18}

    -- Visual presentation hints
    icon VARCHAR(100), -- SF Symbol name or system icon
    color VARCHAR(50), -- Hex color or system color name
    image_url VARCHAR(500), -- Optional background image

    -- Temporal properties
    start_time TIMESTAMP NULL, -- When the event becomes relevant
    end_time TIMESTAMP NULL,   -- When the event expires
    valid_until TIMESTAMP NOT NULL, -- Hard expiration (for cleanup)

    -- Event status
    status VARCHAR(20) NOT NULL CHECK (status IN (
        'pending',    -- Not yet shown to user
        'active',     -- Currently displayed
        'completed',  -- Event finished successfully
        'cancelled',  -- Event no longer relevant
        'expired'     -- Passed valid_until
    )) DEFAULT 'pending',

    -- User interaction tracking
    shown_at TIMESTAMP NULL,
    interacted_at TIMESTAMP NULL,
    dismissed_at TIMESTAMP NULL,

    -- AI generation metadata
    confidence_score DECIMAL(3,2) DEFAULT 0.00, -- 0.00-1.00
    generation_source VARCHAR(50) DEFAULT 'claude', -- Which AI generated this
    context_data JSON DEFAULT ('{}'), -- Context used for generation

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Foreign keys
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    -- Indexes for efficient querying
    INDEX idx_ambient_events_user_id (user_id),
    INDEX idx_ambient_events_type (event_type),
    INDEX idx_ambient_events_status (status),
    INDEX idx_ambient_events_priority (priority),
    INDEX idx_ambient_events_valid_until (valid_until),
    INDEX idx_ambient_events_start_time (start_time),
    INDEX idx_ambient_events_created_at (created_at DESC),
    INDEX idx_ambient_events_active (user_id, status, event_type, valid_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Event Interactions table (track how users interact with ambient events)
CREATE TABLE IF NOT EXISTS event_interactions (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    event_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,

    -- Interaction details
    interaction_type VARCHAR(50) NOT NULL, -- 'tap', 'expand', 'dismiss', 'long_press', etc.
    metadata JSON DEFAULT ('{}'), -- Additional interaction data

    -- Timestamp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (event_id) REFERENCES ambient_events(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_event_interactions_event_id (event_id),
    INDEX idx_event_interactions_user_id (user_id),
    INDEX idx_event_interactions_type (interaction_type),
    INDEX idx_event_interactions_created_at (created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Activity Log table (track user activity patterns for ambient intelligence)
CREATE TABLE IF NOT EXISTS activity_log (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,

    -- Activity details
    action_type VARCHAR(50) NOT NULL, -- 'query', 'view', 'search', 'tap', etc.
    query VARCHAR(500),
    components_shown JSON DEFAULT ('[]'), -- What was displayed
    component_types VARCHAR(255), -- Comma-separated list for quick filtering

    -- Context
    time_of_day VARCHAR(20), -- 'morning', 'afternoon', 'evening', 'night'
    day_of_week VARCHAR(10), -- 'Monday', 'Tuesday', etc.
    location JSON DEFAULT ('{}'), -- Optional location context

    -- Timestamp
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_activity_log_user_id (user_id),
    INDEX idx_activity_log_action_type (action_type),
    INDEX idx_activity_log_timestamp (timestamp DESC),
    INDEX idx_activity_log_patterns (user_id, time_of_day, day_of_week)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Page Cache table (pre-generated UI components from Claude)
CREATE TABLE IF NOT EXISTS page_cache (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,
    cache_key VARCHAR(64) NOT NULL, -- MD5 hash of (user_id + query)

    -- Cache metadata
    cache_type VARCHAR(50) NOT NULL CHECK (cache_type IN ('prediction', 'query', 'context')),
    query VARCHAR(500),

    -- Cached content (AI-generated components)
    components JSON NOT NULL, -- Array of component objects

    -- Relevance scoring
    relevance_score DECIMAL(3,2) DEFAULT 0.00, -- 0.00-1.00

    -- Validity
    valid_until TIMESTAMP NOT NULL,
    hit_count INT DEFAULT 0,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_hit_at TIMESTAMP NULL,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_page_cache_user_id (user_id),
    INDEX idx_page_cache_cache_key (cache_key),
    INDEX idx_page_cache_valid_until (valid_until),
    INDEX idx_page_cache_lookup (user_id, cache_key, valid_until),
    UNIQUE KEY unique_cache_key (user_id, cache_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Generation Queue table (jobs for Claude to process)
CREATE TABLE IF NOT EXISTS generation_queue (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,

    -- Job details
    job_type VARCHAR(50) NOT NULL CHECK (job_type IN (
        'pattern_prediction',
        'ambient_event',
        'query_prediction',
        'context_update'
    )),
    priority INT DEFAULT 1, -- Higher = more important

    -- Job content
    predicted_need TEXT, -- Natural language description
    context_data JSON DEFAULT ('{}'), -- Context for generation

    -- Scheduling
    scheduled_for TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valid_until TIMESTAMP NOT NULL,

    -- Execution tracking
    status VARCHAR(20) NOT NULL CHECK (status IN (
        'queued',
        'processing',
        'completed',
        'failed',
        'cancelled'
    )) DEFAULT 'queued',
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,

    -- Result tracking
    result_cache_key VARCHAR(64), -- Reference to page_cache or ambient_events
    error_message TEXT,

    -- Retry logic
    attempts INT DEFAULT 0,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_generation_queue_user_id (user_id),
    INDEX idx_generation_queue_status (status),
    INDEX idx_generation_queue_priority (priority DESC),
    INDEX idx_generation_queue_scheduled (scheduled_for),
    INDEX idx_generation_queue_processing (status, scheduled_for, valid_until, attempts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Device Tokens table (for push notifications)
CREATE TABLE IF NOT EXISTS device_tokens (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,

    -- Device info
    device_token VARCHAR(255) NOT NULL UNIQUE, -- APNs device token
    device_type VARCHAR(50) NOT NULL, -- 'ios', 'android', etc.
    device_name VARCHAR(100),
    os_version VARCHAR(50),

    -- Notification preferences
    notifications_enabled BOOLEAN DEFAULT TRUE,
    live_activities_enabled BOOLEAN DEFAULT TRUE,
    dynamic_island_enabled BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_device_tokens_user_id (user_id),
    INDEX idx_device_tokens_token (device_token),
    INDEX idx_device_tokens_active (user_id, notifications_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cleanup expired events (run daily via cron/lambda)
-- Events that have passed valid_until should be marked as 'expired'
